# Metadata & Units
meta:
  engine: 4.1.0
units:
  # $default_X fixes web view visualization 
  $default_width: cx
  $default_height: cy
  # Some placement variables to move the USB port around.
  usbx: 20.5
  usby: 6.25+0.05
points:
  zones:
    # Just a big standard 4x12 Planck-alike.
    matrix:
      # Fix position on KiCAD sheet.
      anchor:
        shift: [100, -200]
      columns:
        one:
          key:
            column_net: col1
          rows:
            # LED prev/next custom variables for a SK6812mini-e strand.
            mod.key:
                led_prev: LED36
                led_next: LED37
            bottom.key:
                led_prev: LED35
                led_next: LED36
            home.key:
                led_prev: LED12
                led_next: LED13
            top.key:
                led_prev: LED11
                led_next: LED12
        two:
          key:
            spread: 1cx
            column_net: col2
          rows:
            mod.key:
                led_prev: LED37
                led_next: LED38
            bottom.key:
                led_prev: LED34
                led_next: LED35
            home.key:
                led_prev: LED13
                led_next: LED14
            top.key:
                led_prev: LED10
                led_next: LED11
        three:
          key:
            spread: 1cx
            column_net: col3
          rows:
            mod.key:
                led_prev: LED38
                led_next: LED39
            bottom.key:
                led_prev: LED33
                led_next: LED34
            home.key:
                led_prev: LED14
                led_next: LED15
            top.key:
                led_prev: LED9
                led_next: LED10
        four:
          key:
            spread: 1cx
            column_net: col4
          rows:
            mod.key:
                led_prev: LED39
                led_next: LED40
            bottom.key:
                led_prev: LED32
                led_next: LED33
            home.key:
                led_prev: LED15
                led_next: LED16
            top.key:
                led_prev: LED8
                led_next: LED9
        five:
          key:
            spread:  1cx
            column_net: col5
          rows:
            mod.key:
                led_prev: LED40
                led_next: LED41
            bottom.key:
                led_prev: LED31
                led_next: LED32
            home.key:
                led_prev: LED16
                led_next: LED17
            top.key:
                led_prev: LED7
                led_next: LED8
        six:
          key:
            spread:  1cx
            column_net: col6
          rows:
            mod.key:
                led_prev: LED41
                led_next: LED42
            bottom.key:
                led_prev: LED30
                led_next: LED31
            home.key:
                led_prev: LED17
                led_next: LED18
            top.key:
                led_prev: LED6
                led_next: LED7
        seven:
          key:
            spread:  1cx
            column_net: col6
          rows:
            mod.row_net: row5
            bottom.row_net: row6
            home.row_net: row7
            top.row_net: row8
            mod.key:
                led_prev: LED42
                led_next: LED43
            bottom.key:
                led_prev: LED29
                led_next: LED30
            home.key:
                led_prev: LED18
                led_next: LED19
            top.key:
                led_prev: LED5
                led_next: LED6
        eight:
          key:
            spread:  1cx
            column_net: col5
          rows:
            mod.row_net: row5
            bottom.row_net: row6
            home.row_net: row7
            top.row_net: row8
            mod.key:
                led_prev: LED43
                led_next: LED44
            bottom.key:
                led_prev: LED28
                led_next: LED29
            home.key:
                led_prev: LED19
                led_next: LED20
            top.key:
                led_prev: LED4
                led_next: LED5
        nine:
          key:
            spread:  1cx
            column_net: col4
          rows:
            mod.row_net: row5
            bottom.row_net: row6
            home.row_net: row7
            top.row_net: row8
            mod.key:
                led_prev: LED44
                led_next: LED45
            bottom.key:
                led_prev: LED27
                led_next: LED28
            home.key:
                led_prev: LED20
                led_next: LED21
            top.key:
                led_prev: LED3
                led_next: LED4
        ten:
          key:
            spread:  1cx
            column_net: col3
          rows:
            mod.row_net: row5
            bottom.row_net: row6
            home.row_net: row7
            top.row_net: row8
            mod.key:
                led_prev: LED45
                led_next: LED46
            bottom.key:
                led_prev: LED26
                led_next: LED27
            home.key:
                led_prev: LED21
                led_next: LED22
            top.key:
                led_prev: LED2
                led_next: LED3
        eleven:
          key:
            spread:  1cx
            column_net: col2
          rows:
            mod.row_net: row5
            bottom.row_net: row6
            home.row_net: row7
            top.row_net: row8
            mod.key:
                led_prev: LED46
                led_next: LED47
            bottom.key:
                led_prev: LED25
                led_next: LED26
            home.key:
                led_prev: LED22
                led_next: LED23
            top.key:
                led_prev: LED1
                led_next: LED2
        twelve:
          key:
            spread:  1cx
            column_net: col1
          rows:
            mod.row_net: row5
            bottom.row_net: row6
            home.row_net: row7
            top.row_net: row8
            mod.key:
                led_prev: LED47
                led_next: LED48
            bottom.key:
                led_prev: LED24
                led_next: LED25
            home.key:
                led_prev: LED23
                led_next: LED24
            top.key:
                led_prev: RGB_OUT
                led_next: LED1
      rows:
        mod:
          padding: 1cy
          row_net: row1
        bottom:
          padding: 1cy
          row_net: row2
        home:
          padding: 1cy
          row_net: row3
        top:
          padding: 1cy
          row_net: row4
outlines:
  # Main keyboard area.
  _raw:
    - what: rectangle
      where: true
      size: [1cx+1.5,1cy+1.5]
      fillet: 1.5
  # Key cutouts for visualizations.
  _keys:
    - what: rectangle
      where: true
      size: [1cx-0.5,1cy-0.5]
  # GBA cartridge slot area.
  _controller:
    - what: rectangle
      where:
        ref: [matrix_twelve_bottom]
        shift: [1cx-1.125, 0.5cy]
      size: [1cx+10+7.5, 4cy+1.5]
      fillet: 2
  # The USB port needs a small nubbin' poking out from the main PCB.
  # This rectangle is the main shape.
  _usb:
    - what: rectangle
      where: 
        - ref: matrix_twelve_top
          shift: [usbx, usby+1.75]
      size: [13.25, 6]
      fillet: 1
  # USB nubbin' cutouts. Creates space for a mid-mount USB-C port.
  # The left and right pieces give it a tapered shape.
  _usbcutout:
    - what: rectangle
      where:
        - ref: matrix_twelve_top
          shift: [usbx+0, usby+1.91]
      size: [9.28, 6.64]
  _leftsquare:
    - what: rectangle
      where: 
        - ref: matrix_twelve_top
          shift: [usbx+-7.5, usby]
      size: [3, 5.5]
  _leftcircle:
    - what: circle
      where: 
        - ref: matrix_twelve_top
          shift: [usbx+-10.5, usby+3]
      radius: 4
  _rightsquare:
    - what: rectangle
      where: 
        - ref: matrix_twelve_top
          shift: [usbx+7.5, usby]
      size: [3, 5.5]
  _rightcircle:
    - what: circle
      where: 
        - ref: matrix_twelve_top
          shift: [usbx+10.5, usby+3]
      radius: 4
  # Combining the left and right tapered edges together.
  _leftsupport:
    - _leftsquare
    - -_leftcircle
  _rightsupport:
    - _rightsquare
    - -_rightcircle
  # Final panel outline.
  _panel:
    - _raw
    - _controller
    - _usb
    - _leftsupport
    - _rightsupport
    - -_usbcutout
pcbs:
  type-boy-40:
    # Leverages converted KiCAD 8 footprints.
    template: kicad8
    outlines:
      main:
        outline: _panel
    footprints:
      # Choc Switches
      choc:
        what: choc
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          hotswap: true
          keycaps: true
        adjust:
          rotate: 180
      # SMD Diodes
      diode:
        what: diode-rear
        where: true
        adjust:
          shift: [-8, 1]
          rotate: -90
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      # sk6812mini-e LEDs
      sk6812:
        what: led_sk6812mini-e
        where: true
        params:
          P1: V33_TOGG
          P2: "{{key.led_next}}" #DOUT
          P3: GND
          P4: "{{key.led_prev}}" #DIN
        adjust:
          shift: [0, 5]
          rotate: 0
      # Mounting Holes
      mounting_left_top:
        what: m2mountinghole
        where:
          ref: matrix_one_top
          shift: [0.5cx, -0.5cy]
      mounting_left_bottom:
        what: m2mountinghole
        where:
          ref: matrix_one_mod
          shift: [0.5cx, 0.5cy]
      mounting_left_mid_top:
        what: m2mountinghole
        where:
          ref: matrix_five_top
          shift: [0.5cx, -0.5cy]
      mounting_left_mid_bottom:
        what: m2mountinghole
        where:
          ref: matrix_five_mod
          shift: [0.5cx, 0.5cy]
      mounting_right_mid_top:
        what: m2mountinghole
        where:
          ref: matrix_seven_top
          shift: [0.5cx, -0.5cy]
      mounting_right_mid_bottom:
        what: m2mountinghole
        where:
          ref: matrix_seven_mod
          shift: [0.5cx, 0.5cy]
      mounting_right_top:
        what: m2mountinghole
        where:
          ref: matrix_eleven_top
          shift: [0.5cx, -0.5cy]
      mounting_right_bottom:
        what: m2mountinghole
        where:
          ref: matrix_eleven_mod
          shift: [0.5cx, 0.5cy]
      mounting_right_edge_top:
        what: m2mountinghole
        where:
          ref: matrix_twelve_top
          shift: [0.5cx+1cx+0.85-0.375-0.25+4.75, 0.5cy-2.5-0.15+0.75]
      mounting_right_edge_bottom:
        what: m2mountinghole
        where:
          ref: matrix_twelve_mod
          shift: [0.5cx+1cx+0.85-0.375-0.25+4.75, -0.5cy+2.5+0.15-0.75]
      # GBA Cartridge Slot
      gba:
        what: gba
        where:
          ref: matrix_twelve_bottom
          shift: [1cx-2.75, 0.5cy]
          rotate: -90
        params:
          KB_GPIO1: row8
          KB_GPIO2: row4
          KB_GPIO3: row7
          KB_GPIO4: row3
          KB_GPIO5: row6
          KB_GPIO6: row2
          KB_GPIO7: row5
          KB_GPIO8: row1
          KB_GPIO9: col6
          KB_GPIO10: col5
          KB_GPIO11: col4
          KB_GPIO12: col3
          KB_GPIO13: col2
          KB_GPIO14: col1
      # Mid-mount USB-C port.
      # Wires up to USB pins coming from GBA cart.
      usbc:
        what: usbcmid
        where:
          ref: matrix_twelve_top
          shift: [usbx, 0.5cy+3]
          rotate: 0
        params:
          side: F
          DN1: DNEGIN
          DN2: DNEGIN
          DP1: DPLUSIN
          DP2: DPLUSIN
      # Electro Static Discharge (ESD) Protection.
      # Sits between your USB port and your MCU and makes sure that
      # the things that shouldn't go zap don't go zap.
      esd:
        what: esd
        where:
          ref: matrix_twelve_top
          shift: [usbx-0.5cx-2.125, 0.25cy+1.75]
        params:
          side: F
          DPLUSIN: DPLUSIN
          DNEGIN: DNEGIN
          DPLUSOUT: DATPLUS 
          DNEGOUT: DATMIN
        adjust:
          rotate: -90
      # USB-C Resistors
      res1:
        what: smd805
        where:
          ref: matrix_twelve_top
          shift: [usbx-7.75, 0.5cy-2.375]
          rotate: -90
        params:
          side: F
          from: GND
          to: CC2
      res2:
        what: smd805
        where:
          ref: matrix_twelve_top
          shift: [usbx+7.75, 0.5cy-2.375]
          rotate: -90
        params:
          side: F
          from: GND
          to: CC1
      # Power switch
      power:
        what: power
        where:
          ref: matrix_twelve_mod
          shift: [1cx+6.25, -0.5cy+1.5]
          rotate: 180
        params:
          from: NP
          to: BAT_OUT
          alt: VBAT
      # Reset button
      reset:
        what: button
        where:
          ref: matrix_twelve_mod
          shift: [1cx-3.25, -0.5cy+2.5-0.125]
          rotate: 0
        params:
          side: F
          from: RESET
          to: GND
      # VIK port for additional expansions.
      # Need to flip pin order due to placement on bottom of PCB.
      # Make sure you use a Type-B cable.
      vik:
        what: vik_horizontal
        where:
          ref: matrix_twelve_home
          shift: [1.5cx-3, -0.5cy]
        adjust:
          rotate: 90
        # Stock VIK Pinout
        #params:
        #  side: F
        #  VIK1: V33_JUMPER
        #  VIK2: GND
        #  VIK3: SDA
        #  VIK4: SCL
        #  VIK5: LED48
        #  VIK6: VBUS
        #  VIK7: VIK_GPIO1
        #  VIK8: MOSI
        #  VIK9: VIK_GPIO2
        #  VIK10: VIK_CS
        #  VIK11: MISO
        #  VIK12: SCK
        # Flipped VIK Pinout for bottom-mount Type-B cables.
        params:
          side: B
          VIK1: SCK
          VIK2: MISO
          VIK3: VIK_CS
          VIK4: VIK_GPIO2
          VIK5: MOSI
          VIK6: VIK_GPIO1
          VIK7: VBUS
          VIK8: LED48
          VIK9: SCL
          VIK10: SDA
          VIK11: GND
          VIK12: V33_JUMPER
      # A small cutout for moving the ribbon cable up towards the top of the PCB if you'd like.
      # Not sure how this is actually going to work out in person, but a cartridge will be on top of it anyays.
      vik-cutout:
        what: vik_cutout
        where:
          ref: matrix_twelve_home
          shift: [1.5cx-3+8, -0.5cy]
        adjust:
          rotate: 90
      # The TypePak-Advance provides a permanently-on 3.3v pin, as well as a software toggle-able 3.3v pin.
      # This jumper allows you to specify which pin is connected to the VIK board by default.
      # Defaults to always-on.
      jumper:
        what: jumper
        where:
          ref: matrix_twelve_bottom
          shift: [1cx-3.25-1, 0.5cy-16-3.5]
        adjust:
          rotate: -90
        params:
          side: B
          default: V33_ALWAYS
          out: V33_JUMPER
          alt: V33_TOGG      
      # The VIK logo.
      vik-logo:
        what: vik_logo
        where:
          ref: matrix_twelve_home
          shift: [1.5cx-3+6.75, -0.5cy+20]
        adjust:
          rotate: 0
        params:
          side: F
      # My logo. (I finally made a footprint!)
      fff-logo:
        what: fff_logo
        where:
          ref: matrix_twelve_home
          shift: [1.5cx-3+6.75, -0.5cy-20]
        adjust:
          rotate: 0
        params:
          side: F